In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
 a[0]

1

In [22]:
a[1]

2

In [23]:
import time
import sys

In [24]:
b = range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [25]:
c = np.arange(1000)
print(c.size*c.itemsize)

4000


In [26]:
size = 100000

In [37]:
L1 = range(size)
L2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)


In [41]:
start = time.time()
result = [(x+y) for x,y in zip(L1,L2)]
result = [(x+y) for x,y in zip(L1,L2)]
# print(result)
print('python list took: ',(time.time()- start)*1000)

python list took:  31.026601791381836


In [61]:
start = time.time()
result = A1 + A2
# print(result)
print('numpy list took: ',(time.time()- start)*1000)

numpy list took:  0.9989738464355469


In [65]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
print(a.ndim)
print(a.itemsize)
print(a.shape)

2
4
(3, 2)


In [68]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [71]:
print(a.itemsize)
print(a.shape)

8
(3, 2)


In [73]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [75]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
l = range(5)
l

range(0, 5)

In [80]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [85]:
print('contatenation example:')
print(np.char.add(['hello','hi'], ['abc','xyz']))

contatenation example:
['helloabc' 'hixyz']


In [89]:
print(np.char.multiply('Hello ',3))

Hello Hello Hello 


In [92]:
print(np.char.center('Hello',20,fillchar='-'))

-------Hello--------


In [93]:
print(np.char.capitalize('hello world'))

Hello world


In [95]:
print(np.char.lower(['HELLO WORLD']))
print(np.char.lower('HeLLO'))

['hello world']
hello


In [96]:
print(np.char.upper(['python', 'data']))
print(np.char.upper('python is easy'))

['PYTHON' 'DATA']
PYTHON IS EASY


In [97]:
print(np.char.split('are you coming to the parthy?'))

['are', 'you', 'coming', 'to', 'the', 'parthy?']


In [98]:
print(np.char.splitlines('hello\nhow are you?'))

['hello', 'how are you?']


In [101]:
print(np.char.strip(['nina','admin', 'anaita'],'a'))

['nin' 'dmin' 'nait']


In [104]:
print(np.char.join([':','-'],['dmy','ydm']))

['d:m:y' 'y-d-m']


In [106]:
print(np.char.replace('He is a good dancer','is','was'))

He was a good dancer
